// PLACEHOLDER — regenerated by `npm run db:types` once the local DB is up.
// Keeping it `any`-typed lets the app compile before first generation.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
